name: 上传小程序体验版
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm install -g pnpm
        run: pnpm i
      - name: Build
        run: npm run dev:mp-weixin