name: 上传小程序体验版
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install
        run: pnpm i --no-frozen-lockfile
      - name: Build
        run: npm run build:mp-weixin
      - name: Upload
        uses: lzzone/miniprogram-ci1@main
        with:
          project-path: dist/build/mp-weixin
          private-key: ${{ secrets.PRIVATE_KEY }}        